"""
JSONL dataset loader for multimodal chat-style image fine-tuning datasets.

Loads a JSONL file produced by data_prep.py and exposes it as a Hugging Face
Dataset ready for SFTTrainer LoRA fine-tuning.

Dataset structure:
    train_dataset.jsonl — Each line is a JSON object with keys:
        - messages: list of system/user/assistant messages (multimodal chat format)
"""

import os
from datasets import load_dataset, Image

from .base_dataset import BaseDataset


class SandboxDataset(BaseDataset):
    """Loader for multimodal chat JSONL datasets with image references.

    Loads a JSONL generated by data_prep.py, resolves image paths, and casts
    the image column for automatic PIL loading by the SFTTrainer /
    UnslothVisionDataCollator pipeline.

    Args:
        annotation_path: Path to the JSONL file (e.g. dataset/grid-002/train_dataset.jsonl).
        data_dir: Not used for path resolution (images already have absolute
                  paths in the JSONL), but kept for API consistency with BaseDataset.
    """

    def __init__(
        self,
        annotation_path: str,
        data_dir: str = "",
    ):
        super().__init__(path=annotation_path)
        self.data_dir = data_dir
        self.load()

    def load(self):
        """Load and preprocess the sandbox JSONL dataset.

        Steps:
            1. Load the JSONL via Hugging Face datasets
            2. Extract the first image path from the messages structure
            3. Cast the image column for automatic PIL loading
        """
        if not os.path.isfile(self.path):
            raise FileNotFoundError(
                f"Dataset JSONL not found: {self.path}. "
                "Generate it with src/data_prep.py before training."
            )

        if os.path.getsize(self.path) == 0:
            raise ValueError(
                f"Dataset JSONL is empty: {self.path}. "
                "Regenerate it with src/data_prep.py before training."
            )

        hf_dataset = load_dataset(
            "json",
            data_files=self.path,
            split="train",
        )

        def _extract_image(example):
            """Pull the first image path out of messages into a top-level column."""
            example["image"] = None
            for message in example["messages"]:
                content = message.get("content")
                if not isinstance(content, list):
                    continue
                for part in content:
                    if isinstance(part, dict) and part.get("type") == "image" and part.get("image"):
                        example["image"] = part["image"]
                        return example
            return example

        self.data = hf_dataset.map(_extract_image)
        missing_images = sum(image is None for image in self.data["image"])
        if missing_images:
            raise ValueError(
                f"Dataset JSONL is missing image content in {missing_images} samples: {self.path}"
            )
        self.data = self.data.cast_column("image", Image())
