"""
Sandbox dataset loader for isometric sandbox image scoring.

Loads a JSONL file produced by data_prep.py and exposes it as a
Hugging Face Dataset ready for SFTTrainer LoRA fine-tuning.

Dataset structure:
    train_dataset.jsonl — Each line is a JSON object with keys:
        - messages: list of user/assistant messages (multimodal chat format)
"""

import os
from datasets import load_dataset, Image

from .base_dataset import BaseDataset


class SandboxDataset(BaseDataset):
    """Loader for sandbox scoring JSONL datasets.

    Loads a JSONL generated by data_prep.py, resolves image paths,
    and casts the image column for automatic PIL loading by the
    SFTTrainer / UnslothVisionDataCollator pipeline.

    Args:
        annotation_path: Path to the JSONL file (e.g. dataset/sandbox-001/train_dataset.jsonl).
        data_dir: Not used for path resolution (images already have absolute
                  paths in the JSONL), but kept for API consistency with BaseDataset.

    Example:
        dataset = SandboxDataset(
            annotation_path="dataset/sandbox-001/train_dataset.jsonl",
            data_dir="dataset/sandbox-001",
        )
        print(len(dataset))       # Number of samples
        print(dataset[0])         # First sample
    """

    def __init__(
        self,
        annotation_path: str,
        data_dir: str = "",
    ):
        super().__init__(path=annotation_path)
        self.data_dir = data_dir
        self.load()

    def load(self):
        """Load and preprocess the sandbox JSONL dataset.

        Steps:
            1. Load the JSONL via Hugging Face datasets
            2. Extract the image path from the messages structure
            3. Cast the image column for automatic PIL loading
        """
        hf_dataset = load_dataset(
            "json",
            data_files=self.path,
            split="train",
        )

        def _extract_image(example):
            """Pull the image path out of messages into a top-level 'image' column."""
            user_msg = example["messages"][0]
            for part in user_msg["content"]:
                if part.get("type") == "image":
                    example["image"] = part["image"]
                    break
            return example

        self.data = hf_dataset.map(_extract_image)
        self.data = self.data.cast_column("image", Image())
